---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        io.contiv.tenant: TestTenant
        io.contiv.net-group: backend
        io.contiv.network: TestNet
    spec:
      containers:
        - name: backend
          image: poramus/simple_backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
           - name: MONGO_HOST
             valueFrom:
               configMapKeyRef:
                 name: cluster-config
                 key: mongo.host
           - name: MONGO_PORT
             valueFrom:
               configMapKeyRef:
                 name: cluster-config
                 key: mongo.port
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: backend-port
  selector:
    app: backend
  type: ClusterIP
