---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
  # contiv related stuff
  labels:
    io.contiv.tenant: default
    io.contiv.network: contiv-net
  # end of contiv related stuff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: poramus/simple_backend
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: backend-port
  selector:
    app: backend
  type: ClusterIP
