---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        io.contiv.tenant: default
        io.contiv.network: contiv-net
    spec:
      containers:
        - name: client
          image: poramus/simple_client
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client
spec:
  ports:
  - port: 5004
    protocol: TCP
    name: client-port
  selector:
    app: client
  type: ClusterIP
