---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        io.contiv.tenant: TestTenant
        io.contiv.net-group: client
        io.contiv.network: TestNet
    spec:
      containers:
        - name: client
          image: poramus/simple_client
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
           - name: FRONTEND_HOST
             valueFrom:
               configMapKeyRef:
                 name: cluster-config
                 key: frontend.host
           - name: FRONTEND_PORT
             valueFrom:
               configMapKeyRef:
                 name: cluster-config
                 key: fronted.port
           - name: GENERATOR_HOST
             valueFrom:
               configMapKeyRef:
                 name: cluster-config
                 key: generator.host
           - name: GENERATOR_PORT
             valueFrom:
               configMapKeyRef:
                 name: cluster-config
                 key: generator.port
           - name: REQUEST_TIMEOUT
             valueFrom:
               configMapKeyRef:
                 name: cluster-config
                 key: request.timeout
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client
spec:
  ports:
  - port: 5003
    protocol: TCP
    name: client-port
  selector:
    app: client
  type: ClusterIP
