---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
  # contiv related stuff
  labels:
    io.contiv.tenant: default
    io.contiv.network: contiv-net
    k8s-app: frontend
  # end of contiv related stuff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: poramus/simple_frontend
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  ports:
  - port: 5001
    protocol: TCP
    name: frontend-port
  selector:
    app: frontend
  type: ClusterIP
