---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        io.contiv.tenant: TestTenant
        io.contiv.net-group: frontend
        io.contiv.network: TestNet
    spec:
      containers:
        - name: frontend
          image: poramus/simple_frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  ports:
  - port: 5001
    protocol: TCP
    name: frontend-port
  selector:
    app: frontend
  type: ClusterIP
