---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
        io.contiv.tenant: default
        io.contiv.network: contiv-net
    spec:
      containers:
        - name: generator
          image: poramus/json_generator
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: generator-service
  labels:
    app: generator
spec:
  ports:
  - port: 5002
    protocol: TCP
    name: generator-port
  selector:
    app: generator
  type: ClusterIP
