---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        io.contiv.tenant: default
        io.contiv.network: contiv-net
    spec:
        tolerations:
          - key: node-role.kubernetes.io/master
            effect: NoSchedule
        nodeSelector:
          node-role.kubernetes.io/master: ""
      containers:
        - name: mongo
          image: mongo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          hostPath:
            path: "/data/agh/mongo"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    name: mongo-port
  selector:
    app: mongo
  type: ClusterIP
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: mongo-ingress
#spec:
#  rules:
#    - host: mongo.kube.example.com
#      http:
#        paths:
#          - backend:
#              serviceName: mongo-service
#              servicePort: 27017
